{% set name = "pyhdbpp" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pyhdbpp-{{ version }}.tar.gz
  sha256: 8161c84a01bfabb10e216c5697fa44429dfdab97b0204f87c4b6a6f9f414d7b5


build:
  entry_points:
    - hdbpp-reader = pyhdbpp.reader:main
    - hdb2csv = pyhdbpp.tools.hdb2csv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyyaml
    - pymysql
    - psycopg2

test:
  imports:
    - pyhdbpp
  commands:
    - pip check
    - hdbpp-reader --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/tango-controls/hdbpp/libhdbpp-python
  summary: hdb++ python3 API
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ovallcorba
    - sergirubio
